Feature
jamestucker1988/newsweek pull request #5
Opened 2020-08-09 05:41 UTC by jamestucker1988

This a curriculum-based project to clone a Newsweek webpage. As such I have used bootstrap to a maximum extent. here is the original page <a href="https://www.newsweek.com/">click here</a>.

2020-08-09 05:58 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.

2020-08-09 12:33 UTC, bertil291utn commented on main.css
> +  .display1 {
### Media queries

- [ ] Change all the break points
     - Large 1024px up
     - Medium 768px up
     -  Small 768px down

2020-09-08 06:50 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the TSE's.

2020-09-08 08:17 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @jamestucker1988  NICE WORK SO FAR JUST A FEW MORE CHANGES TO BE MADE. ALSO, GOOD WORK IMPLEMENTING THE CHANGES REQUESTED BY THE PREVIOUS TSE. KINDLY WORK ON THE FOLLOWING :arrow_down: 

- [ ] Kindly add padding between the navigation and the trending section
![edited](https://user-images.githubusercontent.com/32361963/92446804-08fbf900-f1bf-11ea-9ae2-31e0b123416f.jpg)

- [ ] Kindly check the links to some of your images. Some of them are broken as you can see here :arrow_down: 
![edited](https://user-images.githubusercontent.com/32361963/92446877-2c26a880-f1bf-11ea-8817-19a671f7254b.jpg)

- [ ] As stated earlier kindly remove all the border boxes.
![border box](https://user-images.githubusercontent.com/32361963/92447136-87f13180-f1bf-11ea-9679-45ee1009afb8.jpg)

- [ ] Kindly make your footer look like the original site. You need to add some padding on the left and right
![footer sec clone](https://user-images.githubusercontent.com/32361963/92448976-09e25a00-f1c2-11ea-88d5-45911e6d02f5.jpg)

- [ ] Kindly you need to fix this news section. It doesn't resemble the original. Try and make your images fit well.

### YOURS
![news section clone](https://user-images.githubusercontent.com/32361963/92449960-7dd13200-f1c3-11ea-99e6-f95e2dd75f1b.jpg)

### ORIGINAL
![news section original](https://user-images.githubusercontent.com/32361963/92450009-8cb7e480-f1c3-11ea-9153-62e6aa342c48.jpg)

- [ ] At the mobile view, the navigation elements should be inline. Try using flex for that.
![MENU](https://user-images.githubusercontent.com/32361963/92450381-0c45b380-f1c4-11ea-94a2-9376f99efe76.jpg)

- [ ] Kindly remove the borders. Also, remember to fix all broken links for the images.
![more borders](https://user-images.githubusercontent.com/32361963/92450609-5333a900-f1c4-11ea-96c9-6f057e8d7535.jpg)

- [ ]  Kindly at mobile view the images are too small in your more stories section kindly refer to the original site and fix that

![images too small](https://user-images.githubusercontent.com/32361963/92450906-ae659b80-f1c4-11ea-8bf2-478c2e35e56c.jpg)

### IF YOU HAVE ANY QUESTION CONCERNING THE REVIEW KINDLY REACH ME VIA SLACK ON @peterrobert

### HAPPY CODING :computer:

2020-09-10 09:49 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the TSE's.

2020-09-10 16:29 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @jamestucker1988 :wave: 

### I can see that you put a lot of work by doing the required changes from the last TSE, but we still have somethings missing, please check my suggestions below:

- [ ] The last section still doesn't look like the original, you're gonna have to increase the image size, please compare to the original:

![Screenshot from 2020-09-10 13-20-20](https://user-images.githubusercontent.com/59691171/92762747-4603ef00-f369-11ea-910e-c08a77de9760.png)
<br>

- [ ] You still have some images that are not working, please check them:

![Screenshot from 2020-09-10 13-20-33](https://user-images.githubusercontent.com/59691171/92762917-6fbd1600-f369-11ea-96f8-17ad80cfaf97.png)
<br>

- [ ] On mobile screens, your header is still not right, the hamburger icon is going down when it should stay in line with the rest of the content:

![Screenshot from 2020-09-10 13-21-54](https://user-images.githubusercontent.com/59691171/92763110-9aa76a00-f369-11ea-8150-87499b7b723c.png)
<br>

- [ ] Please check your images in this section, they are too big, compare to the original:

![Screenshot from 2020-09-10 13-22-36](https://user-images.githubusercontent.com/59691171/92763172-a85cef80-f369-11ea-98af-3010eb5f4378.png)
<br>

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-11 17:56 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the TSE's.

2020-09-12 01:08 UTC, elmejdki requested changes
# status: require changes :recycle:
## Hi, Great job so far :clap: :100: :+1: but you have a lot of work :hammer: :wrench: :toolbox: to do in order to get your project approved :checkered_flag:

**Please take a look at your page before you submit a code review, it's really messy for example the page should have a max fixed width so it will not get super wide on large screens, also the mobile view is ruined, take a look at the subscribe and newsletter section they are not looking like the original in tablet and mobile view...etc, so please make sure that your page is looking like the original first then ask for a code review if you have trouble don't hesitate to contact any TSE we will be really happy to help you out and don't forget you are here to learn not to get the certificate, cause the certificate will do you nothing if you aren't good.**

## Happy Coding :tophat:

2020-09-14 10:54 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-14 16:01 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey :+1: 

You did a very good job on this project. This is a tough one, and a lot of people have problems with this. We still need to improve in a few aspects. Please exercise patience. You are almost there :100: 

- [ ] The font-sizes are not responsive. The size needs to be smaller in the mobile screen size.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93108136-d6ec0a80-f688-11ea-9a89-01167b18d11f.png) | ![image](https://user-images.githubusercontent.com/61479648/93108177-e23f3600-f688-11ea-8031-a412fcf31939.png) |

- [ ] The layout breaks between 1180px and 900px. Kindly fix that.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93108414-23cfe100-f689-11ea-9a1e-d4b237cb8cbd.png) |![image](https://user-images.githubusercontent.com/61479648/93108455-2f230c80-f689-11ea-8271-46fb82a6649b.png)  |

- [ ] On the More Stories, the text should wrap around the image.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93108579-5b3e8d80-f689-11ea-9279-adf7eabeee1b.png) |![image](https://user-images.githubusercontent.com/61479648/93108598-62659b80-f689-11ea-9e94-a86f7dbc227b.png)  |

- [ ] On 'In The Magazine Section', there is a bug (on the mobile screen size). The next article should be below, not on the side. 
![image](https://user-images.githubusercontent.com/61479648/93108807-a3f64680-f689-11ea-8670-1e4140918588.png)

- [ ] The layout of subscribe section looks different than the original on 882px. 

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93109066-f59ed100-f689-11ea-8aa6-7d74eb188a06.png) | ![image](https://user-images.githubusercontent.com/61479648/93109091-fdf70c00-f689-11ea-92e9-bcd7134dfea1.png) |

- [ ] The footer is also different (look at the padding and font sizes and weight). You need to recheck on all screen sizes.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93109255-35fe4f00-f68a-11ea-8e1c-cdab8b2affbd.png) |![image](https://user-images.githubusercontent.com/61479648/93109276-3d255d00-f68a-11ea-89f2-16e78c25b697.png)  |

#### As stated above, the project looks really good. This is a hard assignment, and you are almost finished.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-09-15 13:40 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-15 13:59 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-15 14:02 UTC, umairarshadbutt commented
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @jamestucker1988 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly read below 👇 and work on the suggested changes.
- [ ] You are missing current date. Please update it

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-15 14:18 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-15 16:10 UTC, arslanbisharat requested changes
### Request changes
I can see you worked hard on this project but I am sorry to inform you that I cannot Approve this project because it is not completed yet.:worried:
It's okay. We are here to learn. Don't get discouraged. Work more hard.
 **Please have a look at the suggestions to get more understanding. :eyes:**

- [ ] Please remove the space around the sides. Have a look [here](https://www.newsweek.com/)

- [ ] Make the center static as in the original page. 
![chrome-capture (4)](https://user-images.githubusercontent.com/58504655/93235857-8fa06f80-f797-11ea-9394-8a84fd81316a.jpg)

- [ ] Add line-break before footer

- [ ] Add Date on nav bar. 

**Please make the changes and request re-review for the given project**
Stay safe:innocent:
### Happy Coding
-------------------------------------------------------------------------------------------------------------------------------------------

**Regards,
Arslan Bisharat
****slack: arslanbisharat******

2020-09-17 03:32 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-17 05:13 UTC, jubaan requested changes
# :wave: Hello @jamestucker1988!

I've :eyes: see you have made great :+1:  improvements to the website!. Getting responsiveness right it's sure not an easy task.

Still there are some issues the clone website has to get right before moving forward.

## Required Changes
### [Mandatory]

- [ ] Extra white space around containers in mobile versions of the clone.
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93420184-1591e880-f874-11ea-9fd7-2d0f2ace251b.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93420145-04e17280-f874-11ea-8bd8-029ad96d8220.png)

- [ ] The ```navbar``` hamburger-menu doesn't appear in all mobile version breakpoints.
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93419923-a2887200-f873-11ea-8b45-92d03051db8f.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93419818-69500200-f873-11ea-8b5c-5bca747ccb90.png)

- [ ] The logo is not resizing correctly.
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93419995-ba5ff600-f873-11ea-96fe-0b5e7a15cf0f.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93419877-897fc100-f873-11ea-8496-bf5d27fa5620.png)

- [ ] The debate section is not displaying properly
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93420704-1ecf8500-f875-11ea-9353-3e62a43f0dc0.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93420416-75888f00-f874-11ea-9773-7dac2540f6ff.png)

- [ ] Out of place section 
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93421134-1e83b980-f876-11ea-9910-1780a3426b05.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93421089-0f047080-f876-11ea-9aa2-bf8541080ea9.png)

- [ ] No sticky navbar in mobile version
### ORIGINAL
![image](https://user-images.githubusercontent.com/25774518/93421340-b1bcef00-f876-11ea-8f00-3aa4e28f78b9.png)
### CLONE
![image](https://user-images.githubusercontent.com/25774518/93421319-a36ed300-f876-11ea-8fc3-63d5f159fd21.png)

- [ ]  Subscribe and newsletter section not responsive in smallest view.
![image](https://user-images.githubusercontent.com/25774518/93421529-33ad1800-f877-11ea-889e-7565b91879a1.png)

### [NOTES] 
This section is not mandatory nor optional just personal comments or suggestions that may help you improve your coding skills.

- I've couldn't help to notice that the code has a strange formatting, I think this could be related to a formatter like 'Prettier' or 'Beutifier', try to configure it in a way it improves readability.
:-1:  Not that readable
```
¦ ¦ ¦ ¦ <a
¦ ¦ ¦ ¦ ¦ href="#"
¦ ¦ ¦ ¦ ¦ class="text-dark text-decoration-none font-weight-bold mx-auto"
¦ ¦ ¦ ¦ ¦ >World</a
¦ ¦ ¦ ¦ >
```
:+1:  This improves redability :100: 
```
¦ ¦ ¦ ¦ <a href="#" class="text-dark text-decoration-none font-weight-bold mx-auto">
¦ ¦ ¦ ¦ ¦ ¦ World
¦ ¦ ¦ ¦ </a>
```
- Try to maintain the code DRY (Don't Repeat Yourself). The CSS has a lot of ```.display1```, ```.display2```, so on and so on.... selectors. 
This could be only:
```
    .display-none { display: none }
```
:+1: But the better alternative is to take advantage of ```d-none``` bootstrap class. [Bootstrap display properties](https://getbootstrap.com/docs/4.0/utilities/display/) 
- In general the clone is not taking full advantage of Bootstrap classes, because of this, the main css is duplicating framework classes. Example:
``` fixed { position: fixed; }``` is equal to boostrap ```position-fixed```
``` .absolute{ position: absolut; }``` is equal to boostrap ```position-absolute```
``` .float-left { float: left; }``` is equal to boostrap ``` float-left```
... to mention a few examples.

### [RELATED LINKS]
[Boostrap position](https://getbootstrap.com/docs/4.0/utilities/position/)
[Bootstrap display properties](https://getbootstrap.com/docs/4.0/utilities/display/) 
[Boostrap float](https://getbootstrap.com/docs/4.0/utilities/float/)

2020-09-18 15:46 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-18 18:05 UTC, blackpintz requested changes
# Status: Changes Required

## Hello Anand, Great work implementing the changes.

## General Requirements:

1). **The is no sticky navbar.**

2). **Subscribe and newsletter section not responsive in smallest view.**

![](https://user-images.githubusercontent.com/25774518/93421529-33ad1800-f877-11ea-889e-7565b91879a1.png).

3). **The debate section is still not displaying properly, as explained in the previous tse review, for the mobile screen view.** 

4). **Still on the debate section, please add some top bottom spacing and the double line in the middle as it is in the original.**

   original   |  clone
------------ | ---------
![debate_original](https://user-images.githubusercontent.com/38922385/93629199-8d851d80-f9f0-11ea-8c6f-fa206badda3b.png) |  ![debate_clone](https://user-images.githubusercontent.com/38922385/93629227-98d84900-f9f0-11ea-87af-859e6352d276.png)


5). **The signup form is not displaying properly in the mobile view.**
   original   |  clone
------------ | ---------
![sign_up_section_original](https://user-images.githubusercontent.com/38922385/93628485-4c403e00-f9ef-11ea-96ba-5ee795e8286b.png)  |  ![sign_up_clone](https://user-images.githubusercontent.com/38922385/93628516-5b26f080-f9ef-11ea-8b35-bfc88aeb1593.png)

# Optional

1). **Define a height for your images, on the rightmost part of the news, tech and travel section, so they don't look to vertically stretched when on medium and mobile screen views.**

## Good luck 😃.
### PS: If you want to reach out, send me a message on slack (@Rose Wanjohi)

2020-09-20 02:24 UTC, jamestucker1988 commented
this project is a curriculum-based project where we have to clone newsweek.com. proficiency in bootstrap is expected as such I have tried to use bootstrap to the full extent.
-I have made all the changes requested by the previous TSE's.

2020-09-20 05:12 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello team! A great effort in improving the project! :sunglasses: 

Please there is still one issue left, the navbar is not sticky yet in mobile version.

- [ ] No sticky navbar in mobile. 

![image](https://user-images.githubusercontent.com/25774518/93694778-62282e80-fad5-11ea-9b9f-731013c6e2a3.png)

## Keep up the great work :muscle: , I admire :clap:  the progress and advances you have made with the project! :100:

2020-09-20 07:44 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

Hi @jamestucker1988, congratulations on building such a great and amazing project 👍. Also, taking time to implement some of the changes requested by the TSEs.  I see you have implemented the sticky nav-bar on the mobile as requested by the previous TSE. 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project. Furthermore, I have mentioned some nice to have changes. I encourage you to work on them before moving to the next project.

- Rename your HTML file from `index1.html` to `index.html`
- Give the `body` a background of say `#f4f5f6` and your container elements `#fff` so you can have that nice look just like the original.

2020-09-20 07:44 UTC, acushlakoncept commented on main.css
> +@media (min-width: 768px) and (max-width: 991.98px) {
Use the recommended breakpoints:
- Large 1024px up
- Medium 768px up
- Small 768px down
Since we are following the mobile-first approach, we will stick to the `min-width` only approach.

2020-09-20 07:44 UTC, acushlakoncept commented on index1.html
> +        </ul>
- Having `text-muted` and `fontsize-8` moved to `<ul>` would save a lot of repeated codes across every `<li>` element.
- Also using `border-right` would minimize the line of code in a great deal instead of hard coding the dividers. The will mean eliminating `<li class="list-inline-item text-muted fontsize-8  d-none d-lg-inline d-md-inline d-xl-inline ">|</li>` completely.

2020-09-20 07:44 UTC, acushlakoncept commented on index1.html
> +  <div class="container sticky-top">
Adding `.container { max-width: 1600px; }` or 1300px would make your layout a lot close to looking like the original

2020-09-20 07:44 UTC, acushlakoncept commented on index1.html
> +      </div>
Representing each of the article item with the `article` semantic tag would not just make your codebase look good but greatly improve SEO optimization on your site.

I encourage you to use more semantic tags instead of just div tags. It helps in debugging also. This [article](https://www.w3schools.com/html/html5_semantic_elements.asp) might be helpful to you.

2020-09-20 09:42 UTC, merged